title: Your awesome title
author: Sergio Murillo Mendez
email: sergio.murillo.mendez@gmail.com
description: Sergio Murillo Mendez CV

theme: minima

# social links
twitter_username: sergiomume # DO NOT include the @ character, or else the build will fail!
github_username:  sergiomume # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
